<?php

require_once 'id.php';
$PERSONALITIES = [
    'fleeter' => [
        'subtypes' => [
            'swarm' => [
                'ship_caps' => [
                    GID_F_SC => 500000,
                    GID_F_LF => 500000,
                    GID_F_CRUISER => 50000,
                    GID_F_PROBE => 100000,
                    GID_F_BATTLECRUISER => 8000
                ],
                'priority_ships' => [GID_F_LF, GID_F_SC, GID_F_CRUISER, GID_F_BATTLECRUISER, GID_F_PROBE],
            ],
            'speed' => [
                'ship_caps' => [
                    GID_F_LF => 300000,
                    GID_F_CRUISER => 200000,
                    GID_F_PROBE => 100000,
                    GID_F_DESTRO => 5000
                ],
                'priority_ships' => [GID_F_BATTLECRUISER, GID_F_CRUISER, GID_F_LF, GID_F_DESTRO, GID_F_PROBE],
            ],
            'smasher' => [
                'ship_caps' => [
                    GID_F_LC => 20000,
                    GID_F_RECYCLER => 30000,
                    GID_F_PROBE => 500000,
                    GID_F_BOMBER => 30000,
                    GID_F_SAT => 10000,
                    GID_F_DESTRO => 50000,
                    GID_F_DEATHSTAR => 10000,
                    GID_F_BATTLECRUISER => 150000,
                ],
                'priority_ships' => [
                    GID_F_SC, GID_F_LC, GID_F_LF,
                    GID_F_HF, GID_F_CRUISER,
                    GID_F_BATTLESHIP,
                    GID_F_COLON,
                    GID_F_RECYCLER,
                    GID_F_PROBE,
                    GID_F_BOMBER,
                    GID_F_SAT,
                    GID_F_DESTRO,
                    GID_F_DEATHSTAR,
                    GID_F_BATTLECRUISER],
            ],
            'balanced' => [
                'ship_caps' => [
                    GID_F_SC => 50000,
                    GID_F_LC => 100000,
                    GID_F_LF => 500000,
                    GID_F_HF => 100000,
                    GID_F_CRUISER => 200000,
                    GID_F_BATTLESHIP => 50000,
                    GID_F_COLON => 1,
                    GID_F_RECYCLER => 100000,
                    GID_F_PROBE => 500000,
                    GID_F_BOMBER => 30000,
                    GID_F_SAT => 10000,
                    GID_F_DESTRO => 50000,
                    GID_F_DEATHSTAR => 10000,
                    GID_F_BATTLECRUISER => 150000,
                ],
                'priority_ships' => [
                    GID_F_SC, GID_F_LC, GID_F_LF,
                    GID_F_HF, GID_F_CRUISER, GID_F_BATTLESHIP, GID_F_COLON,
                    GID_F_RECYCLER, GID_F_PROBE, GID_F_BOMBER, GID_F_SAT,
                    GID_F_DESTRO, GID_F_DEATHSTAR, GID_F_BATTLECRUISER],
            ],
            'default_subtype' => 'balanced',
        ],
        'building_caps' => [
            GID_B_METAL_MINE => 28,
            GID_B_CRYS_MINE => 24,
            GID_B_DEUT_SYNTH => 6,
            GID_B_SOLAR => 25,
            GID_B_FUSION => 0,
            GID_B_ROBOTS => 10,
            GID_B_NANITES => 4,
            GID_B_SHIPYARD => 16,
            GID_B_METAL_STOR => 5,
            GID_B_CRYS_STOR => 5,
            GID_B_DEUT_STOR => 6,
            GID_B_RES_LAB => 12,
            GID_B_TERRAFORMER => 4,
            GID_B_ALLY_DEPOT => 4,
            GID_B_LUNAR_BASE => 5,
            GID_B_PHALANX => 5,
            GID_B_JUMP_GATE => 5,
            GID_B_MISS_SILO => 4,
        ],
        'priority_buildings' => [
            GID_B_ROBOTS, GID_B_SHIPYARD, GID_B_SOLAR,
            GID_B_METAL_MINE, GID_B_CRYS_MINE, GID_B_DEUT_SYNTH,
            GID_B_METAL_STOR, GID_B_CRYS_STOR, GID_B_DEUT_STOR,
            GID_B_NANITES, GID_B_MISS_SILO, GID_B_LUNAR_BASE,
            GID_B_PHALANX, GID_B_JUMP_GATE, GID_B_ALLY_DEPOT,
            GID_B_TERRAFORMER, GID_B_RES_LAB
        ],
        'research_caps' => [
            GID_R_ESPIONAGE => 12,
            GID_R_WEAPON => 18,
            GID_R_SHIELD => 18,
            GID_R_ARMOUR => 16,
            GID_R_COMBUST_DRIVE => 14,
            GID_R_IMPULSE_DRIVE => 14,
            GID_R_LASER_TECH => 12,
            GID_R_ION_TECH => 10,
            GID_R_HYPERSPACE => 8,
            GID_R_PLASMA_TECH => 15,
            GID_R_ENERGY => 12,
            GID_R_COMPUTER => 10,
            GID_R_IGN => 9,
            GID_R_EXPEDITION => 12,
            GID_R_GRAVITON => 1,
        ],
        'priority_research' => [
            GID_R_WEAPON, GID_R_SHIELD, GID_R_ARMOUR,
            GID_R_HYPERSPACE, GID_R_IMPULSE_DRIVE, GID_R_COMBUST_DRIVE,
            GID_R_ENERGY,
            GID_R_ESPIONAGE,
            GID_R_COMPUTER,
        ],
    ],
    'miner' => [
        'default_subtype' => 'balanced',
        'subtypes' => [
            'pure' => [
                'ship_caps' => [
                    GID_F_SC => 500,
                    GID_F_LF => 100,
                ],
                'priority_ships' => [GID_F_SC, GID_F_LF],
            ],
            'trader' => [
                'ship_caps' => [
                    GID_F_LC => 5000,
                    GID_F_SC => 1000,
                    GID_F_LF => 200,
                    GID_F_RECYCLER => 100,
                ],
                'priority_ships' => [
                    GID_F_LC, GID_F_SC,
                    GID_F_RECYCLER, GID_F_LF],
            ],
            'balanced' => [
                'ship_caps' => [
                    GID_F_SC => 1000,
                    GID_F_LC => 500,
                    GID_F_LF => 500,
                    GID_F_HF => 200,
                    GID_F_CRUISER => 50,
                    GID_F_RECYCLER => 100,
                ],
                'priority_ships' => [
                    GID_F_SC, GID_F_LC,
                    GID_F_LF, GID_F_HF,
                    GID_F_CRUISER, GID_F_RECYCLER],
            ],
        ],
        'building_caps' => [
            GID_B_METAL_MINE => 30,
            GID_B_CRYS_MINE => 28,
            GID_B_DEUT_SYNTH => 26,
            GID_B_SOLAR => 30,
            GID_B_FUSION => 15,
            GID_B_METAL_STOR => 25,
            GID_B_CRYS_STOR => 25,
            GID_B_DEUT_STOR => 25,
            GID_B_ROBOTS => 10,
            GID_B_NANITES => 5,
            GID_B_SHIPYARD => 5,
            GID_B_RES_LAB => 10,
            GID_B_TERRAFORMER => 0,
            GID_B_ALLY_DEPOT => 0,
            GID_B_LUNAR_BASE => 0,
            GID_B_PHALANX => 0,
            GID_B_JUMP_GATE => 0,
            GID_B_MISS_SILO => 0,
        ],
        'priority_buildings' => [
            GID_B_METAL_MINE, GID_B_CRYS_MINE, GID_B_DEUT_SYNTH,
            GID_B_SOLAR, GID_B_FUSION,
            GID_B_METAL_STOR, GID_B_CRYS_STOR, GID_B_DEUT_STOR,
            GID_B_ROBOTS, GID_B_NANITES,
            GID_B_RES_LAB,
            GID_B_SHIPYARD
        ],
        'research_caps' => [
            GID_R_ENERGY => 15,
            GID_R_LASER_TECH => 12,
            GID_R_ION_TECH => 10,
            GID_R_PLASMA_TECH => 8,
            GID_R_ESPIONAGE => 8,
            GID_R_COMPUTER => 10,
            GID_R_COMBUST_DRIVE => 10,
            GID_R_IMPULSE_DRIVE => 8,
            GID_R_HYPERSPACE => 5,
            GID_R_WEAPON => 5,
            GID_R_SHIELD => 5,
            GID_R_ARMOUR => 5,
            GID_R_HYPER_DRIVE => 4,
            GID_R_IGN => 0,
            GID_R_EXPEDITION => 0,
            GID_R_GRAVITON => 0,
        ],
        'priority_research' => [
            GID_R_ENERGY,
            GID_R_ESPIONAGE,
            GID_R_COMPUTER,
            GID_R_COMBUST_DRIVE,
            GID_R_IMPULSE_DRIVE,
            GID_R_HYPERSPACE,
            GID_R_WEAPON,
            GID_R_SHIELD,
            GID_R_ARMOUR,
            GID_R_HYPER_DRIVE,
            GID_R_LASER_TECH,
            GID_R_ION_TECH,
            GID_R_PLASMA_TECH,
        ],
    ]
];

